name: Blender Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/blendergrid/blender:latest
      options: --user root
      volumes:
        - /tmp:/tmp

    steps:
      - name: Inspect environment
        run: |
          # print environment information
          echo "Distribution: $(cat /etc/issue | head -n 1 | cut -d ' ' -f 1-3)"
          echo "User: $(whoami):$(groups)"

          # symlink `blender` command
          ln -s /usr/local/blender/blender /usr/bin/blender
          echo "Blender version: $(blender --background --quiet)"
          blender -b -q --python-expr "import bpy; print(f'Python in Blender: {bpy}')"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests in Blender..."
          blender -b -P system-under-test/tests/run_tests.py
