name: Blender Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.io/blendergrid/blender:latest
      options: --user root

    steps:
      - name: Check blendergrid container and add blender to PATH
        run: |
          echo "Running in container: $(cat /etc/issue | head -n 1 | cut -d ' ' -f 1)"
          ln -s /usr/local/blender/blender /usr/bin/blender
          echo "Blender version: $(blender --background --quiet)"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check that running python in blender works
        run: |
          blender --background --python-expr "import bpy; print(f'hello from python in blender: {bpy.app.version_string}')"
